### Dummy submission
POST http://localhost:8077/register
Content-Type: application/json

{
  "email":"developer@visitscotland.com",
  "first_name": "ほせ",
  "last_name": "Developer",
  "company": "BusyNessie Ltd",
  "consents" : "",
  "activity_source": "Dev - Carbon Calculator", "activity_description":"Business Support Hub Online Booking System (Activities) download",
  "g-recaptcha-response":"03AFcWeA5gJEe3or5LX3lqRKfqvtbQQhqVjwvUe0O6KgERJmPVfCBLI2l0EjOEjuV4GAIRZ5Ju04uWmeQ2hVY4bjO_E2mx2NOLyKfaBapinMGOld7zUdHN5uk8dg5-ThfiBwAlyz8K6MIHZb_H6tCz0ju4zlNfwNFaDZvA03Aa7RUN_LiLh-hIWidMqORjZ2zAV-Wm_-PuPSqMTBFvrao6geqVBo2r8_qHIyJ9Glwox40AVPoUI657yfPj-LCqDjhuWntZrByVh_ZgEb36o-qVA7A68ClBGj7ouAsb8FzApwPlzoQavQKoKylkvGu7QrB-77v_r8NrcrO2EUQK8v1clgLATq5qvBZuZuqRtfN9IOkSk3igK0XOGmS4aeI-0LcLx6Kps39UFHpKL2NrTXa1PFKfRqxZtUBAc8niafByov5EKavsGudNjR-gapbL1zmJZWft85PfK3dOqh9y2gwQL2gZFzW56AXXO_VzB5lIh6FikuSaZ7TPyhf5vMBCPThzOi_0fHLMIH7NaVyBpUkejNGYuS3aQUBkEhQy8fKzgHxDWEGgJAqNXWXJrennhvGdD_jgefZEjm6zVt4iUuFmgi_-zfPtBXiDTUn3freCs4AqILYzMzNM9jdKs-oikt5qzeq_BJfabyVMlk9o-vgikDGQmc00WapOArN6Buu4zUGz4DYzN_lFsPirfPa6A9UM1pX3nrrVG1V1s"
}

###Dummy submission to breg
POST  https://api.visitscotland.net/dev/submit/breg/form/stakeholder
Content-Type: application/json

{
  "email":"developer+001@visitscotland.com",
  "first_name": "ほせ",
  "last_name": "Developer",
  "company": "BusyNessie Ltd",
  "postcode": "XXXXX",
  "activity_source": "Dev - Carbon Calculator", "activity_description":"Business Support Hub Online Booking System (Activities) download",
  "g-recaptcha-response":"03AFcWeA5gJEe3or5LX3lqRKfqvtbQQhqVjwvUe0O6KgERJmPVfCBLI2l0EjOEjuV4GAIRZ5Ju04uWmeQ2hVY4bjO_E2mx2NOLyKfaBapinMGOld7zUdHN5uk8dg5-ThfiBwAlyz8K6MIHZb_H6tCz0ju4zlNfwNFaDZvA03Aa7RUN_LiLh-hIWidMqORjZ2zAV-Wm_-PuPSqMTBFvrao6geqVBo2r8_qHIyJ9Glwox40AVPoUI657yfPj-LCqDjhuWntZrByVh_ZgEb36o-qVA7A68ClBGj7ouAsb8FzApwPlzoQavQKoKylkvGu7QrB-77v_r8NrcrO2EUQK8v1clgLATq5qvBZuZuqRtfN9IOkSk3igK0XOGmS4aeI-0LcLx6Kps39UFHpKL2NrTXa1PFKfRqxZtUBAc8niafByov5EKavsGudNjR-gapbL1zmJZWft85PfK3dOqh9y2gwQL2gZFzW56AXXO_VzB5lIh6FikuSaZ7TPyhf5vMBCPThzOi_0fHLMIH7NaVyBpUkejNGYuS3aQUBkEhQy8fKzgHxDWEGgJAqNXWXJrennhvGdD_jgefZEjm6zVt4iUuFmgi_-zfPtBXiDTUn3freCs4AqILYzMzNM9jdKs-oikt5qzeq_BJfabyVMlk9o-vgikDGQmc00WapOArN6Buu4zUGz4DYzN_lFsPirfPa6A9UM1pX3nrrVG1V1s"
}

###Dummy submission to Trace API to authenticate and get a token (API TOKEN REQUIRED)
POST https://api.staging.traceyour.events/v2/auth/token
Content-Type: application/json
Authorization: {{$random.internet.password}}

{}

### Dummy submission to Trace API to get a list of events
GET  https://api.staging.traceyour.events/v2/visitscotland/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiI2YTU3YjJhNzY1MDA5YTI3MTA0NGY2ZGIiLCJ0eXBlIjo2LCJpYXQiOjE3ODQxOTY0ODIsImV4cCI6MTc4NDE5NzM4Mn0.aBuZm46gIEbdjwU2FM2JPPDuABIO-WDyDMdUqcgJBgk

{
    "email":"developer+0001@visitscotland.com",
    "firstName": "José ほせ",
    "lastName": "Developer of VisitScotland",
    "businessName": "BusyNessie Ltd",
    "experieinceLevel": "I_HAVE_NO_EXPERIENCE_WITH_CARBON_MEASUREMENT_AND_REPORTING",
    "businessSector": "ACCOMMODATION",
    "businessSubSector": "HOTELS",
    "location": "CITY_OF_EDINBURGH",
    "businessType": "LIMITED_COMPANY",
    "ftStaff": "11-250",
    "consents" : "carbon_calculator, All right!",
    "vsUID": "{{$random.uuid}}"
}