spring.application.name=vs-carbon-calculator-gateway
spring.mvc.log-resolved-exception=false
#Allowed origins (Production Only)
allowed_origin=https://develop-brc-support.visitscotland.org,\
  https://release-brc-support.visitscotland.org,\
  https://support.visitscotland.org

# Recaptcha properties
recaptcha.enabled=true
recaptcha.publickey=
recaptcha.secretkey=

#Breg configuration
breg.service-url=https://api.visitscotland.net/dev/submit/breg/form/stakeholder
breg.remove-properties=tourismBusiness,inScotland,emissionsUpdate,terms,handover,answerOne,answerTwo,answerThree,answerFour,separatorOne,separatorTwo
breg.enabled=true

#Isla Integration configuration
trace-api.enabled=true
trace-api.base-url=https://api.staging.traceyour.events/v2
trace-api.remove-properties=g-recaptcha-response,activity_description,activity_source,activity_code,\
  consents,consentList,tourismBusiness,inScotland,supportNewsletter,emissionsUpdate,terms,handover,answerOne,answerTwo,answerThree,answerFour,separatorOne,separatorTwo
trace-api.api-key=${TRACE_API_STAGING_KEY:no-key}

#Mail
spring.mail.host=mail.visitscotland.com
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
notification.email.enabled=true
notification.email.subject=Carbon Calculator Error Report
notification.email.recipients=
notification.email.sender=noreply@visitscotland.com




