spring.application.name=vs-carbon-calculator
server.port=8077
spring.mvc.log-resolved-exception=false

# Recaptcha properties
recaptcha.enabled=true
recaptcha.publickey=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
recaptcha.secretkey=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

#Breg configuration
breg.service-url=https://api.visitscotland.net/dev/submit/breg/form/stakeholder
breg.remove-properties=
breg.enabled=true

#Isla Integration configuration
trace-api.enabled=true
trace-api.base-url=https://api.staging.traceyour.events/v2
trace-api.remove-properties=g-recaptcha-response,activity_description,activity_source,activity_code,consents
trace-api.key=${TRACE_API_STAGING_KEY:no-key}


