server.port=8077
allowed_origin=*
notification.email.recipients=Jose.Calcines+ccg@visitscotland.com,brian.gibb@visitscotland.com,Corina.Baillie@visitscotland.com,julia.razlivaieva@visitscotland.com
recaptcha.publickey=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
recaptcha.secretkey=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe


