spring.application.name=vs-carbon-calculator
server.port=8077

breg.service.url=https://api.visitscotland.net/dev/submit/breg/form/stakeholder
breg.remove.properties=
breg.enabled=false

# Global properties
recaptcha.enabled=true
recaptcha.publickey=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
recaptcha.secretkey=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
